name: thrifty_nifty_app
description: App for Thrifty Nifty API

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.4+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  get: ^4.3.8
  loading_indicator: ^3.0.2
  google_fonts: ^2.1.0
  liquid_pull_to_refresh: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true